### ISSUE TITLE
Dies after a few seconds.

### ISSUE THREAD

**Issue by lethjakman** [codeskyblue/docker-gogs#1]
This container seems to die after a few seconds. I had it working twice previously, both times it has died then continuously dies every time I start it in less than 5 seconds. This is the command I'm using to run docker:

```bash
docker run -d  --link postgres:postgres -p 22:22 -p 3000:3000 -v /var/gogs:/data codeskyblue/docker-gogs
```

Any idea what's causing this? I can't seem to find a helpful log (however the gogs log seems to be starting with sqlite3.)

Thank you!

**Comment by codeskyblue** [comment]
Fixed ssh connect problem. Maybe this problem fix too.

**Comment by lethjakman** [comment]
The -d was causing the issue because I was starting it from within a systemd file. I only found documentation on it recently but it causes it to hang up. Thank you for your help!
