### ISSUE TITLE
Crash upon crtl-c while cloning

### ISSUE THREAD

**Issue by Dasoren** [codeskyblue/docker-gogs#11]
I have you docker of gogs running. default settings. Added a new user and cloned a git repo on the server added to a group by another user. When the new user crtl-c well the repo is being compressed or downloaded the docker img crashes.

here is the docker command I am running, `docker run -d -p 23:22 -p 3000:3000 -v /var/gogs:/data codeskyblue/docker-gogs`

Log from /var/gogs/gogs/log/serv.log
```
2015/07/29 05:22:25 [serve.go:81 func·001()] [F] Fail to execute git command: signal: broken pipe
2015/07/29 05:25:02 [serve.go:81 func·001()] [F] Fail to execute git command: signal: broken pipe
2015/07/29 05:29:13 [serve.go:81 func·001()] [F] Fail to execute git command: signal: broken pipe
2015/07/29 05:32:32 [serve.go:81 func·001()] [F] Fail to execute git command: signal: broken pipe
```

log from /var/gogs/gogs/log/gogs.log
```
2015/07/29 05:31:16 [I] Log Mode: File(Info)
2015/07/29 05:31:16 [I] Redis Enabled
2015/07/29 05:31:16 [I] Cache Service Enabled
2015/07/29 05:31:16 [I] Session Service Enabled
2015/07/29 05:31:16 [I] Mail Service Enabled
2015/07/29 05:31:16 [I] Register Mail Service Enabled
2015/07/29 05:31:16 [I] Notify Mail Service Enabled
2015/07/29 05:31:16 [I] SQLite3 Enabled
2015/07/29 05:31:16 [I] Run Mode: Production
2015/07/29 05:31:16 [I] Listen: http://0.0.0.0:3000
```

Docker keeps running in the ps, but the docker-proxy and the docker img stop running in the ps

What info would you like from me to help clear this up?

**Comment by codeskyblue** [comment]
do you have some crash log?

**Comment by Dasoren** [comment]
I am sorry, I did not see this message till now. I do not have a crash log that I can find. I am new to using docker and gogs. I looked though the gogs logs and that is what I put in the post. If you can tell me where to look for the log I will check. I am running Ubuntu 14.04, normal install.

I have at this point uninstalled docker and this repo and am using gogs right on the system. It has not had any issues.
