### ISSUE TITLE
ssh support

### ISSUE THREAD

**Issue by ripienaar** [codeskyblue/docker-gogs#3]
The problem with ssh is that the GOGS_CUSTOM=/data/gogs is not set.

We can make this work by setting "PermitUserEnvironment yes" in sshd_config and then creating ~git/.ssh/environment with GOGS_CUSTOM=/data/gogs in it.

Do you have plans to try and make this work? Will try hack up a PR

**Comment by codeskyblue** [comment]
thanks for you pr.
