### ISSUE TITLE
update version

### ISSUE THREAD

**Issue by wirmachenbunt** [codeskyblue/docker-gogs#6]
it would be really cool if you could update the repo to the recent gogs version.
cheers

**Comment by jens-a-e** [comment]
it seems done, according to the build history https://registry.hub.docker.com/u/codeskyblue/docker-gogs/builds_history/30834/
thx!

**Comment by codeskyblue** [comment]
Yes, but since my network is not very well, It is not very easy for me to check if the build result is OK? So if you checked ok, this issue can be closed.

**Comment by mbirth** [comment]
It seems there's a problem with your SQLite version: gogits/gogs#1319 .

**Comment by codeskyblue** [comment]
I tested it, but it seems ok, I can create new repo, etc... maybe I guess, the sqlite.db need some upgrade. You can create a fully new gogs with that docker image, to see if that error happen again.

**Comment by mbirth** [comment]
Yes, I suspect the problem is with upgrading the database from 0.5 to 0.6. I'll test creating a brand new Gogs instance later.

**Comment by mbirth** [comment]
I just updated the Dockerfile and now the upgrade worked fine. Thanks!
