### ISSUE TITLE
Mac setup

### ISSUE THREAD

**Issue by puppybits** [codeskyblue/docker-gogs#9]
It looks like the git user couldn't write the gogs.db file. I was able to set the username to root (and again on the install page) and it all worked. Thanks for the docker image!

Here's the run command I used to get it to work on Mac.  

    docker run --name=gogs -d \
      -e USER=root \
      -e USERAME=root \
      -p 10022:22 \
      -p 10080:3000 \
      -v ~/Desktop/gogs:/data \
      codeskyblue/docker-gogs ./gogs web

**Comment by codeskyblue** [comment]
Maybe you need use `chmod` to change prop.
